# Generated by Django 3.0.2 on 2020-01-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('encryptedPhrase', models.CharField(max_length=255)),
                ('requested', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
